dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://dubbohost:2181
  scan:
    base-packages: com.tunion.dubbo.provider
spring:
  application:
    name: dubbo-provider-demo

